# Generated by Django 3.0.8 on 2020-07-22 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20200722_2241'),
        ('documentos', '0002_documento_proprietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.Funcionario'),
            preserve_default=False,
        ),
    ]
